{% set name = "hdijupyterutils" %}
{% set version = "0.12.9" %}
{% set hash_type = "sha256" %}
{% set hash_val = "2946b7199e5c4d8e6b4a48d6d8f5505f1348ea2189be4a3fdb539073a7f15691" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://github.com/jupyter-incubator/sparkmagic/archive/{{ version }}.tar.gz
    {{ hash_type }}: {{ hash_val }}

build:
    noarch: python
    number: 0
    script: cd {{ name }} && python -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - python
        - pip
    run:
        - python
        - ipython >=4.0.2
        - nose
        - mock
        - ipywidgets >=5.0.0
        - ipykernel >=4.2.2
        - jupyter >=1
        - pandas >=0.17.1
        - numpy
        - notebook >=4.2


test:
    imports:
        - hdijupyterutils

about:
    home: https://github.com/jupyter-incubator/sparkmagic/tree/master/hdijupyterutils
    license: BSD 3-clause
    summary: Project with useful classes/methods for all projects created by the HDInsight team at Microsoft around Jupyter
    license_file: LICENSE.md

extra:
  recipe-maintainers:
    - danielfrg
