{% set name = "hdijupyterutils" %}
{% set version = "0.22.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hdijupyterutils-{{ version }}.tar.gz
  sha256: 6a9f31cd841f75f695499ec411403da751c5e1ae92b75e8908469151ede61e97

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - ipykernel >=4.2.2
    - ipython >=4.0.2
    - ipywidgets >5.0.0
    - jupyter >=1
    - notebook >=4.2
    - numpy >=1.16.5
    - pandas <3.0.0
    - python >={{ python_min }}

test:
  imports:
    - hdijupyterutils
  commands:
    - pip check || true
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jupyter-incubator/sparkmagic/hdijupyterutils
  summary: 'HdiJupyterUtils: Utils for Jupyter projects from HDInsight team'
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - dbast
    - devstein
