{% set name = "hdijupyterutils" %}
{% set version = "0.17.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hdijupyterutils-{{ version }}.tar.gz
  sha256: 22458763df4e2023ea916bb486a50e8c58ba6e46a0740094f10dac79c8ae4c84

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - ipykernel >=4.2.2
    - ipython >=4.0.2
    - ipywidgets >5.0.0
    - jupyter >=1
    - mock
    - nose
    - notebook >=4.2
    - numpy
    - pandas >=0.17.1
    - python >=3.6

test:
  imports:
    - hdijupyterutils
  commands:
    - pip check || true
  requires:
    - pip

about:
  home: https://github.com/jupyter-incubator/sparkmagic/hdijupyterutils
  summary: 'HdiJupyterUtils: Utils for Jupyter projects from HDInsight team'
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - dbast
