{% set name = "hdijupyterutils" %}
{% set version = "0.19.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hdijupyterutils-{{ version }}.tar.gz
  sha256: 1ad26177509c816755bfdb327e1343dddc2729258f3fde097f79d18f1c5cf52a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - ipykernel >=4.2.2
    - ipython >=4.0.2
    - ipywidgets >5.0.0
    - jupyter >=1
    - mock
    - nose
    - notebook >=4.2
    - numpy
    - pandas >=0.17.1
    - python >=3.6

test:
  imports:
    - hdijupyterutils
  commands:
    - pip check || true
  requires:
    - pip

about:
  home: https://github.com/jupyter-incubator/sparkmagic/hdijupyterutils
  summary: 'HdiJupyterUtils: Utils for Jupyter projects from HDInsight team'
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - dbast
