travis:
  secure:
    BINSTAR_TOKEN: Ioeb3cwLly1C5r3tde5MsdtqMtQJtYzc3ybPDit15/ti9h2tAWm2MINxKqNLmRbTiN9btdIn+8AniK43CAWVxPq92odCgtF54sqOkIQKb6wc0/x1Bw3Zc4smYBV0cXiSxoSM1KA4H8IOBv9l4lynkoE2y7wcJt27s2PpcjDirdGdXqMefPSywcNIaX120JFaXkt6naZDcPS3jd0x0yyWgWzSO+kTe298IXVvjxDF5aCZWJcVO/WVSagF1CWkGnzh/2NqMUwQ0aqtWoSSHTIsmL7l0Yq3G4HpnG9RBqbWk9P7wNEzQYsvNm+tU09K2IytuMrCKpVf7I1NFlxldGWqIpnQZVQCpGPhVA16vIA21LC/0AStLoizRPw9QaWwIo192jyTzEByFs33eI8SBift8bSFvFVsSZkA7Li9tfEUbUyDYG/QGNtYAOqBK+BSAGdSc7nFXgS3mKVQ9gm4FSSby7UoXYeA2jY6c/0CGAN5sqQGVVgWJ49cgzo0fk5an0xEKQpAcifkjvwtWZx2LeHisMRYqCBr1f5exSz4noemuGqkBaNceqEfbWNDV26uYk6lYTX8Y8OHEPvCFhLjhPdTL6RlVI7NuUQhOLvz4kQIv7rFFbRS8LWU+zMPqikSRquSVgUoojBBwjPfFijVNiAtvYyr/JkqxWsDMsDK+62zBDI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
